spring:
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    connect-timeout: 2000ms
    command-timeout: 2000ms

  logging:
    level:
      io.lettuce.core: DEBUG
      org.springframework.data.redis: DEBUG